[unstable]
build-std = ["core", "alloc", "panic_abort", "compiler_builtins"]
build-std-features = ["panic_immediate_abort", "compiler-builtins-mem"]

[target.'cfg(windows)']
rustflags = [
    "-Csymbol-mangling-version=v0",
    "-Zlocation-detail=none",
    "-Zunstable-options",
    "-Zfunction-sections=yes",
    "-Cpanic=abort",
]
